# **Assignment** `Day-14`

In [347]:
# Import Library

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## **Read the data**

In [348]:
# read csv
df = pd.read_csv('../data/googleplaystore.csv')

In [349]:
# read data
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

## **Size**

In [350]:
df['Size'].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '470k',
       '226k', '240k', '89k', '234k', '257k', '861k', '467k', '157k',
       '44k', '676k', '67k', '552k', '885k', '1020k', '582k', '619k'],
      dtype=object)

## **Install**

In [351]:
df['Price'].unique()

array(['0', '$4.99', '$3.99', '$6.99', '$1.49', '$2.99', '$7.99', '$5.99',
       '$3.49', '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49',
       '$10.00', '$24.99', '$11.99', '$79.99', '$16.99', '$14.99',
       '$1.00', '$29.99', '$12.99', '$2.49', '$10.99', '$1.50', '$19.99',
       '$15.99', '$33.99', '$74.99', '$39.99', '$3.95', '$4.49', '$1.70',
       '$8.99', '$2.00', '$3.88', '$25.99', '$399.99', '$17.99',
       '$400.00', '$3.02', '$1.76', '$4.84', '$4.77', '$1.61', '$2.50',
       '$1.59', '$6.49', '$1.29', '$5.00', '$13.99', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$19.90', '$8.49', '$1.75',
       '$14.00', '$4.85', '$46.99', '$109.99', '$154.99', '$3.08',
       '$2.59', '$4.80', '$1.96', '$19.40', '$3.90', '$4.59', '$15.46',
       '$3.04', '$4.29', '$2.60', '$3.28', '$4.60', '$28.99', '$2.95',
       '$2.90', '$1.97', '$200.00', '$89.99', '$2.56', '$30.99', '$3.61',
       '$394.99', '$1.26', '$1.20', '$1.04'], dtype=object)

In [352]:
# Cheak columns

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  int64
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10841 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10839 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 1.1+ MB

### Defining each column in MD style

**App** : The name of the app

**Category** : The category of the app

**Rating** : The rating of the app in the Play Store

**Reviews** : The number of reviews of the app

**Size** : The size of the app

**Install** : The number of installs of the app

**Type** : The type of the app (Free/Paid)

**Price** : The price of the app (0 if it is Free)

**Content Rating** : The appropiate target audience of the app

**Genres**: The genre of the app

**Last Updated** : The date when the app was last updated

**Current Ver** : The current version of the app

**Android Ver** : The minimum Android version required to run the app

# Assignment: Write down all the numeric variables and make them numeric?

1. size
2. install
3. price

## **_Price_**
---

**In summary**, this code accomplishes the following:

1. It defines a function called `convert_price` to process and convert string representations of prices. This function removes dollar signs ('$'), commas (',') used as thousands separators, and any leading/trailing white spaces to prepare the string for conversion.

2. The function attempts to convert the cleaned string to a floating-point number. If it encounters any exceptions (e.g., due to invalid input), it returns None.

3. The `convert_price` function is applied to the 'Price' column of the DataFrame 'df', cleaning and converting all values in that column.

4. The 'Price' column is then converted to a numeric data type, with errors coerced to NaN values, using the `pd.to_numeric` function.

5. Finally, it retrieves the unique values in the 'Price' column after processing.

In [353]:
df['Size'].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '470k',
       '226k', '240k', '89k', '234k', '257k', '861k', '467k', '157k',
       '44k', '676k', '67k', '552k', '885k', '1020k', '582k', '619k'],
      dtype=object)

In [354]:
# Define a function that converts a string representing a price to a numeric value
def convert_price(price_str):
    try:
        # Remove any dollar signs ('$'), commas (',') used as thousands separators, and leading/trailing white spaces
        price_str = price_str.replace('$', '').replace(',', '').strip()
        
        # Convert the cleaned string to a floating-point number
        return float(price_str)
    except:
        # If any exceptions occur (e.g., due to invalid input), return None
        return None

# Apply the convert_price function to the 'Price' column of the DataFrame 'df'
df['Price'] = df['Price'].apply(convert_price)

# Convert the 'Price' column to a numeric type, with errors coerced to NaN values
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

# Retrieve unique values in the 'Price' column after processing
unique_prices = df['Price'].unique()

In [355]:
unique_prices

array([  0.  ,   4.99,   3.99,   6.99,   1.49,   2.99,   7.99,   5.99,
         3.49,   1.99,   9.99,   7.49,   0.99,   9.  ,   5.49,  10.  ,
        24.99,  11.99,  79.99,  16.99,  14.99,   1.  ,  29.99,  12.99,
         2.49,  10.99,   1.5 ,  19.99,  15.99,  33.99,  74.99,  39.99,
         3.95,   4.49,   1.7 ,   8.99,   2.  ,   3.88,  25.99, 399.99,
        17.99, 400.  ,   3.02,   1.76,   4.84,   4.77,   1.61,   2.5 ,
         1.59,   6.49,   1.29,   5.  ,  13.99, 299.99, 379.99,  37.99,
        18.99, 389.99,  19.9 ,   8.49,   1.75,  14.  ,   4.85,  46.99,
       109.99, 154.99,   3.08,   2.59,   4.8 ,   1.96,  19.4 ,   3.9 ,
         4.59,  15.46,   3.04,   4.29,   2.6 ,   3.28,   4.6 ,  28.99,
         2.95,   2.9 ,   1.97, 200.  ,  89.99,   2.56,  30.99,   3.61,
       394.99,   1.26,   1.2 ,   1.04])

## **_Install_**
---

**In summary**, this code does the following:
1. It defines a function called `convert_installs` to process and convert string representations of the number of installs to integers. The function removes plus signs ('+'), commas (',') used as thousands separators, and any leading/trailing white spaces to prepare the string for conversion.

2. The function attempts to convert the cleaned string to an integer. If it encounters any exceptions (e.g., due to invalid input), it returns None.

3. The `convert_installs` function is applied to the 'Installs' column of the DataFrame 'df', cleaning and converting all values in that column.

4. The 'Installs' column is then converted to a numeric data type, with errors coerced to NaN values, using the `pd.to_numeric` function.

5. Finally, it retrieves the unique values in the 'Installs' column after processing.

In [356]:
df['Installs'].unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '0+', '0'], dtype=object)

In [357]:
# Define a function that converts a string representing the number of installs to an integer
def convert_installs(installs_str):
    try:
        # Remove any plus signs ('+'), commas (',') used as thousands separators, and leading/trailing white spaces
        installs_str = installs_str.replace('+', '').replace(',', '').strip()
        
        # Convert the cleaned string to an integer
        return int(installs_str)
    except:
        # If any exceptions occur (e.g., due to invalid input), return None
        return None

# Apply the convert_installs function to the 'Installs' column of the DataFrame 'df'
df['Installs'] = df['Installs'].apply(convert_installs)

# Convert the 'Installs' column to a numeric type, with errors coerced to NaN values
df['Installs'] = pd.to_numeric(df['Installs'], errors='coerce')

# Retrieve unique values in the 'Installs' column after processing
unique_installs = df['Installs'].unique()

In [358]:
unique_installs

array([     10000,     500000,    5000000,   50000000,     100000,
            50000,    1000000,   10000000,       5000,  100000000,
       1000000000,       1000,  500000000,         50,        100,
              500,         10,          1,          5,          0],
      dtype=int64)

## **_Size_**

**In summary**, this code accomplishes the following:

1. It defines a function called `convert_size` to process and convert string representations of file sizes. The function identifies if the size is in megabytes ('M') or kilobytes ('k'), and performs the conversion accordingly. If the string doesn't end with 'M' or 'k', it returns None, which indicates an invalid format.

2. The `convert_size` function is applied to the 'Size' column of the DataFrame 'df', cleaning and converting all values in that column.

3. Rows with 'Size' values that are None (indicating invalid formats) are dropped from the DataFrame.

4. The 'Size' column is then converted to a numeric data type, with errors coerced to NaN values, using the `pd.to_numeric` function.

5. Finally, it retrieves the unique values in the 'Size' column after processing.

In [359]:
df['Size'].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '470k',
       '226k', '240k', '89k', '234k', '257k', '861k', '467k', '157k',
       '44k', '676k', '67k', '552k', '885k', '1020k', '582k', '619k'],
      dtype=object)

In [360]:
# Define a function that clears and converts a string representing file size to a numeric value
def convert_size(size_str):
    try:
        if size_str.endswith('M'):
            # If the size string ends with 'M', remove 'M' and convert to a float
            return float(size_str.replace('M', ''))
        elif size_str.endswith('k'):
            # If the size string ends with 'k', remove 'k' and convert to a float, then divide by 1024
            return float(size_str.replace('k', '')) / 1024
        else:
            # If the string doesn't end with 'M' or 'k', return None (likely indicating an invalid format)
            return None
    except:
        # If any exceptions occur, return None (used as a default/fallback value)
        return None

# Apply the convert_size function to the 'Size' column of the DataFrame 'df'
df['Size'] = df['Size'].apply(convert_size)

# Drop rows with 'Size' values that are None (indicating invalid formats)
df = df.dropna(subset=['Size'])

# Convert the 'Size' column to a numeric type, with errors coerced to NaN
df['Size'] = pd.to_numeric(df['Size'], errors='coerce')

# Retrieve unique values in the 'Size' column after processing
unique_sizes = df['Size'].unique()

In [361]:
unique_sizes

array([1.90000000e+01, 1.40000000e+01, 8.70000000e+00, 2.50000000e+01,
       2.80000000e+00, 5.60000000e+00, 2.90000000e+01, 3.30000000e+01,
       3.10000000e+00, 2.80000000e+01, 1.20000000e+01, 2.00000000e+01,
       2.10000000e+01, 3.70000000e+01, 2.70000000e+00, 5.50000000e+00,
       1.70000000e+01, 3.90000000e+01, 3.10000000e+01, 4.20000000e+00,
       7.00000000e+00, 2.30000000e+01, 6.00000000e+00, 6.10000000e+00,
       4.60000000e+00, 9.20000000e+00, 5.20000000e+00, 1.10000000e+01,
       2.40000000e+01, 9.40000000e+00, 1.50000000e+01, 1.00000000e+01,
       1.20000000e+00, 2.60000000e+01, 8.00000000e+00, 7.90000000e+00,
       5.60000000e+01, 5.70000000e+01, 3.50000000e+01, 5.40000000e+01,
       1.96289062e-01, 3.60000000e+00, 5.70000000e+00, 8.60000000e+00,
       2.40000000e+00, 2.70000000e+01, 2.50000000e+00, 1.60000000e+01,
       3.40000000e+00, 8.90000000e+00, 3.90000000e+00, 2.90000000e+00,
       3.80000000e+01, 3.20000000e+01, 5.40000000e+00, 1.80000000e+01,
       1.10000000e+00, 2.20000000e+00, 4.50000000e+00, 9.80000000e+00,
       5.20000000e+01, 9.00000000e+00, 6.70000000e+00, 3.00000000e+01,
       2.60000000e+00, 7.10000000e+00, 3.70000000e+00, 2.20000000e+01,
       7.40000000e+00, 6.40000000e+00, 3.20000000e+00, 8.20000000e+00,
       9.90000000e+00, 4.90000000e+00, 9.50000000e+00, 5.00000000e+00,
       5.90000000e+00, 1.30000000e+01, 7.30000000e+01, 6.80000000e+00,
       3.50000000e+00, 4.00000000e+00, 2.30000000e+00, 7.20000000e+00,
       2.10000000e+00, 4.20000000e+01, 7.30000000e+00, 9.10000000e+00,
       5.50000000e+01, 2.24609375e-02, 6.50000000e+00, 1.50000000e+00,
       7.50000000e+00, 5.10000000e+01, 4.10000000e+01, 4.80000000e+01,
       8.50000000e+00, 4.60000000e+01, 8.30000000e+00, 4.30000000e+00,
       4.70000000e+00, 3.30000000e+00, 4.00000000e+01, 7.80000000e+00,
       8.80000000e+00, 6.60000000e+00, 5.10000000e+00, 6.10000000e+01,
       6.60000000e+01, 7.71484375e-02, 8.40000000e+00, 1.15234375e-01,
       4.40000000e+01, 6.78710938e-01, 1.60000000e+00, 6.20000000e+00,
       1.75781250e-02, 5.30000000e+01, 1.40000000e+00, 3.00000000e+00,
       5.80000000e+00, 3.80000000e+00, 9.60000000e+00, 4.50000000e+01,
       6.30000000e+01, 4.90000000e+01, 7.70000000e+01, 4.40000000e+00,
       4.80000000e+00, 7.00000000e+01, 6.90000000e+00, 9.30000000e+00,
       8.10000000e+00, 3.60000000e+01, 8.40000000e+01, 9.70000000e+01,
       2.00000000e+00, 1.90000000e+00, 1.80000000e+00, 5.30000000e+00,
       4.70000000e+01, 5.42968750e-01, 5.13671875e-01, 7.60000000e+01,
       7.60000000e+00, 5.90000000e+01, 9.70000000e+00, 7.80000000e+01,
       7.20000000e+01, 4.30000000e+01, 7.70000000e+00, 6.30000000e+00,
       3.26171875e-01, 3.40000000e+01, 9.30000000e+01, 6.50000000e+01,
       7.90000000e+01, 1.00000000e+02, 5.80000000e+01, 5.00000000e+01,
       6.80000000e+01, 6.40000000e+01, 6.70000000e+01, 6.00000000e+01,
       9.40000000e+01, 2.26562500e-01, 9.90000000e+01, 6.09375000e-01,
       9.50000000e+01, 8.30078125e-03, 4.00390625e-02, 2.85156250e-01,
       1.07421875e-02, 8.00000000e+01, 1.70000000e+00, 7.40000000e+01,
       6.20000000e+01, 6.90000000e+01, 7.50000000e+01, 9.80000000e+01,
       8.50000000e+01, 8.20000000e+01, 9.60000000e+01, 8.70000000e+01,
       7.10000000e+01, 8.60000000e+01, 9.10000000e+01, 8.10000000e+01,
       9.20000000e+01, 8.30000000e+01, 8.80000000e+01, 6.87500000e-01,
       8.41796875e-01, 8.77929688e-01, 3.69140625e-01, 2.59765625e-01,
       3.66210938e-01, 1.30000000e+00, 9.52148438e-01, 9.57031250e-01,
       4.10000000e+00, 8.90000000e+01, 6.79687500e-01, 5.31250000e-01,
       5.12695312e-01, 8.98437500e-01, 7.60742188e-01, 8.33007812e-01,
       7.03125000e-01, 6.96289062e-01, 7.53906250e-01, 3.10546875e-01,
       5.66406250e-02, 2.35351562e-01, 1.91406250e-01, 8.36914062e-01,
       4.98046875e-02, 9.30664062e-01, 8.44726562e-01, 2.45117188e-01,
       9.08203125e-01, 5.27343750e-01, 3.05664062e-01, 7.28515625e-01,
       1.98242188e-01, 2.53906250e-02, 3.06640625e-01, 2.33398438e-01,
       3.62304688e-01, 2.14843750e-01, 7.12890625e-01, 7.38281250e-01,
       8.88671875e-02, 2.86132812e-01, 1.66015625e-02, 7.22656250e-02,
       1.36718750e-02, 3.09570312e-01, 7.61718750e-02, 9.02343750e-01,
       8.80859375e-01, 7.98828125e-01, 7.91015625e-02, 9.16992188e-01,
       1.65039062e-01, 4.39453125e-02, 4.63867188e-01, 9.42382812e-01,
       9.00000000e+01, 5.32226562e-01, 5.95703125e-02, 2.76367188e-01,
       6.39648438e-01, 6.97265625e-01, 9.08203125e-02, 8.51562500e-01,
       1.18164062e-01, 3.14453125e-01, 1.00000000e+00, 9.53125000e-01,
       1.67968750e-01, 2.32421875e-01, 5.36132812e-01, 2.01171875e-01,
       9.31640625e-01, 4.33593750e-01, 7.00195312e-01, 2.05078125e-01,
       5.94726562e-01, 3.00781250e-01, 6.88476562e-01, 2.98828125e-01,
       8.82812500e-01, 4.61914062e-01, 1.70898438e-01, 3.41796875e-01,
       3.74023438e-01, 4.43359375e-01, 4.11132812e-01, 6.83593750e-02,
       7.92968750e-01, 4.31640625e-01, 8.22265625e-01, 4.07226562e-01,
       4.02343750e-01, 4.48242188e-01, 4.66796875e-01, 3.27148438e-01,
       7.63671875e-01, 7.04101562e-01, 4.19921875e-01, 4.18945312e-01,
       1.87500000e-01, 1.95312500e-01, 4.49218750e-01, 7.10937500e-01,
       4.84375000e-01, 7.96875000e-01, 4.04296875e-01, 4.94140625e-01,
       8.66210938e-01, 5.98632812e-01, 2.37304688e-01, 5.55664062e-01,
       7.59765625e-01, 6.66992188e-01, 5.78125000e-01, 3.11523438e-01,
       1.81640625e-01, 8.20312500e-01, 6.31835938e-01, 1.86523438e-01,
       3.64257812e-01, 4.26757812e-01, 5.83984375e-01, 6.99218750e-01,
       5.71289062e-01, 9.58984375e-01, 2.16796875e-01, 2.13867188e-01,
       5.37109375e-02, 9.25781250e-01, 3.15429688e-01, 6.74804688e-01,
       4.99023438e-01, 9.28710938e-01, 9.40429688e-01, 2.44140625e-02,
       5.41015625e-01, 3.42773438e-01, 2.63671875e-02, 8.00781250e-02,
       2.03125000e-01, 8.91601562e-01, 5.01953125e-01, 5.38085938e-01,
       2.83203125e-02, 1.00585938e-01, 8.76953125e-01, 7.25585938e-01,
       1.13281250e-01, 1.49414062e-01, 2.04101562e-01, 3.44726562e-01,
       4.87304688e-01, 1.68945312e-01, 5.83007812e-01, 7.90039062e-01,
       1.19140625e-01, 4.01367188e-01, 3.90625000e-01, 7.82226562e-01,
       7.68554688e-01, 2.31445312e-01, 4.88281250e-02, 6.27929688e-01,
       9.62890625e-01, 9.47265625e-02, 5.03906250e-01, 8.17382812e-01,
       7.61718750e-01, 9.38476562e-01, 2.62695312e-01, 1.95312500e-02,
       4.86328125e-01, 5.85937500e-01, 7.31445312e-01, 6.26953125e-01,
       8.60351562e-01, 7.03125000e-02, 6.40625000e-01, 5.86914062e-01,
       2.15820312e-01, 2.22656250e-01, 1.05468750e-01, 9.17968750e-01,
       1.71875000e-01, 3.22265625e-02, 6.47460938e-01, 3.32031250e-02,
       9.19921875e-01, 2.52929688e-01, 1.60156250e-01, 4.47265625e-01,
       2.39257812e-01, 6.14257812e-01, 2.73437500e-02, 2.81250000e-01,
       7.56835938e-01, 7.66601562e-01, 6.21093750e-01, 8.94531250e-01,
       9.70703125e-01, 3.01757812e-01, 4.73632812e-01, 8.92578125e-01,
       8.81835938e-01, 5.93750000e-01, 4.88281250e-01, 5.27343750e-02,
       5.48828125e-01, 8.27148438e-01, 9.34570312e-01, 6.71875000e-01,
       7.91992188e-01, 2.63671875e-01, 4.68750000e-02, 3.21289062e-01,
       5.10742188e-01, 8.99414062e-01, 8.53515625e-01, 9.58007812e-01,
       7.65625000e-01, 2.73437500e-01, 2.34375000e-02, 5.05859375e-01,
       7.36328125e-01, 8.71093750e-01, 1.50390625e-01, 8.39843750e-01,
       3.55468750e-01, 3.77929688e-01, 6.11328125e-01, 1.57226562e-01,
       8.58398438e-01, 3.80859375e-02, 9.47265625e-01, 1.66015625e-01,
       1.37695312e-01, 1.56250000e-01, 1.40625000e-01, 1.39648438e-01,
       1.85546875e-01, 3.67187500e-01, 1.88476562e-01, 2.40234375e-01,
       7.12890625e-02, 6.42578125e-01, 9.68750000e-01, 2.47070312e-01,
       4.10156250e-01, 3.94531250e-01, 4.58984375e-01, 2.20703125e-01,
       2.34375000e-01, 8.69140625e-02, 2.28515625e-01, 2.50976562e-01,
       8.40820312e-01, 4.56054688e-01, 1.53320312e-01, 4.29687500e-02,
       6.60156250e-01, 6.54296875e-02, 5.39062500e-01, 8.64257812e-01,
       9.96093750e-01, 5.68359375e-01, 6.04492188e-01])

## _**After Converting**_ `Size`, `Install` & `Price`

In [362]:
df.head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6,50000,Free,0.0,Everyone,Art & Design,"March 26, 2017",1.0,2.3 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19.0,50000,Free,0.0,Everyone,Art & Design,"April 26, 2018",1.1,4.0.3 and up
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29.0,1000000,Free,0.0,Everyone,Art & Design,"June 14, 2018",6.1.61.1,4.2 and up
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791,33.0,1000000,Free,0.0,Everyone,Art & Design,"September 20, 2017",2.9.2,3.0 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1,10000,Free,0.0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up

In [363]:
df.dtypes

App                object
Category           object
Rating            float64
Reviews             int64
Size              float64
Installs            int64
Type               object
Price             float64
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object